/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.0.1/userguide/multi_project_builds.html
 */

rootProject.name = "kosmparser"

pluginManagement {
    val kotlinVersion: String by settings
    val dokkaVersion: String by settings
    val detektVersion: String by settings
    val versionsVersion: String by settings
    val testLoggerVersion: String by settings
    plugins {
        kotlin("jvm") version kotlinVersion
        id("io.gitlab.arturbosch.detekt") version detektVersion
        id("com.github.ben-manes.versions") version versionsVersion
        id("com.adarshr.test-logger") version testLoggerVersion
        id("org.jetbrains.dokka") version dokkaVersion
        id("org.jetbrains.dokka-javadoc") version dokkaVersion
    }
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.5.0"
}
